default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  timeout: 5000
development:
  <<: *default
  username: postgres
  password: naveen123
  database: nr_backend_development 
production:
  <<: *default
  username: postgres
  password: naveen123
  database: nr_prod
